// ~~ Generated by projen. To modify, edit .projenrc.js and run "pnpm exec projen".

import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
	name: 'prisma-model-types',
	clean: true,
	declaration: true,
	failOnWarn: false,
})
